# Generated by Django 3.1.12 on 2025-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20),
        ),
    ]
