# Generated by Django 3.1.12 on 2025-02-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_auto_20250206_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')]),
        ),
    ]
