# Generated by Django 3.1.12 on 2025-02-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0003_auto_20250206_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
