# Generated by Django 3.1.12 on 2025-02-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0004_auto_20250206_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='college',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='name',
            field=models.TextField(),
        ),
    ]
